### ISSUE TITLE
RTSP ANNOUNCE request failed: 500

### ISSUE THREAD

**Issue by gwrichard** [irtimmer/moonlight-embedded#812] opened 2021-04-13 05:12 UTC
Please provide the following info.

**_NVidia Geforce Experience version: 3.22.0.32
**Moonlight Embedded version: 2.4.10-master-5b6639c
**Moonlight Embedded source: https://github.com/irtimmer/moonlight-embedded
**Moonlight Embedded running on: Raspberry Pi 3b+
**Moonlight Embedded running on distribution: Raspbian

**Verbose output `-verbose` of Moonlight Embedded:**

Moonlight Embedded 2.4.10 (PI;MMAL;SDL;X11;ALSA;PULSE;EMBEDDED)
Connect to 192.168.10.102...
NVIDIA NVIDIA GeForce GTX 1660 SUPER, GFE 3.22.0.32 (gs_04_31_29754594, 7.1.431.0)
Platform Raspberry Pi (Broadcom)
Loading mappingfile /usr/local/share//moonlight/gamecontrollerdb.txt
Stream 1280 x 720, 30 fps, 5000 kbps
Initializing platform...done
Resolving host name...done
Starting RTSP handshake...RTSP ANNOUNCE request failed: 500
failed: 500
Cleaning up platform...done

**What is the expected result?**
Moonlight runs and starts streaming from host

**What happens instead of that?**
App launches on host, but moonlight gives ..RTSP ANNOUNCE request failed: 500 error.

Note: I was initially getting the error RTSP handshake failed... RTSP message too long (describe failed: -1). I updated RTSP_MAX_RESP_SIZE to 64000 RtspConnection.c and reinstalled moonlight.

This cleared the first error, but now results in the RTSP Annnounce request failed.

**Comment by irtimmer** [comment] 2021-04-13 07:49
Duplicate of #810

**Closed by irtimmer** 2021-04-13 07:49 UTC
Labels: duplicate
