### ISSUE TITLE
Moonlight on orange pi

### ISSUE THREAD

**Issue by Glip** [irtimmer/moonlight-embedded#451] opened 2016-12-27 10:48 UTC
Please provide the following info.

**_NVidia Geforce Experience version:_** 3.2.0.96
**Moonlight Embedded version:** Moonlight Embedded 2.2.2 (EMBEDDED;PI)
**Moonlight Embedded running on:** OrangePI

**Output of Moonlight Embedded:**

Starting video stream...* failed to open vchiq instance

**What is the expected result?**
Want to see my steam window :)

**What happens instead of that?**
Try to start moonlight, but he not start with that error.
On my PC Steam started.
I understant, what vchiq its for rpi. But how change video driver (???) for orange pi?

**Comment by irtimmer** [comment] 2016-12-27 10:54
Duplicate of #249

**Closed by irtimmer** 2016-12-27 10:54 UTC
