### ISSUE TITLE
Binding additional mouse buttons & windows shortcuts

### ISSUE THREAD

**Issue by forteh** [irtimmer/moonlight-embedded#300] opened 2016-01-22 23:29 UTC
Hi,
Not sure if this is an existing issue or has been covered elsewhere (had a look through the wiki and google and not come back with anything meaningful).

I have a logitech g700 mouse and k400 plus keyboard connected to the rpiB+, the mouse I know I can bind the keys through hardware profiling (via windows) but moonlight doesnt seem to forward the button presses onto windows.  For example, the thumb buttons work as forward and back in raspbian but do nothing when streaming windows; is it possible to enable these additional buttons on the mouse?

Likewise certain keyboard shortcuts dont work, ctrl alt del being the main one, yet ctrl+C/ctrl+V works fine.

Another oddity (perhaps with the k400 keyboard) is that the apostrophe (and when shifted, the @ symbol) returns a hash and shifted tilde.  The hash/tilde key returns a backslash / vertical bar and the backslash / vertical bar key on the left of the keyboard does nothing.

**Comment by irtimmer** [comment] 2016-04-03 17:04
The Gamestream protocol doesn't support additional buttons of the mouse.

Keyboard problem is a duplicate of #108

**Closed by irtimmer** 2016-04-03 17:04 UTC
