### ISSUE TITLE
Wrong Mapping with Dualshock 3 PS3 Controller. Bad response.

### ISSUE THREAD

**Issue by ZeonXP** [irtimmer/moonlight-embedded#293] opened 2016-01-12 21:20 UTC
Hello, I have a problem mapping a DS3 controller. I have an original one and a fake. Both have the same problem when I map them. Always wired with an USB, not bluetooth. In EmulationStation it works perfectly without any problem.
I use the command (directly on retropie or via ssh) "moonlight map controllername.map".
First of all I receive the message "can't map reverse_z and reverse_rz" or something like this. Then I can map Left Analog Right, Up, Thumb and the same for Right Analog (no Analog Down and Left). After this I finish mapping the rest of the buttons.

When I start the stream with:
moonlight stream 192.168.1.12 -1080 -60fps -mapping /opt/retropie/configs/moonlight/controllername.map -app Steam
The streaming starts well but the input is wrong. If I push any direction it keeps pressed like infinite to the left or down and doesn't stop, so it is unusable.

Any idea how to fix it?
Raspberry 2 with Retropie with Moonlight 2.1.2
Windows 10
Thank you!

EDIT: It seems the same problem like #264

**Comment by irtimmer** [comment] 2016-04-03 16:32
Duplicate of #264

**Closed by irtimmer** 2016-04-03 16:32 UTC
Labels: duplicate
