### ISSUE TITLE
Xbox One Wireless controller doesn't work on games, only on Steam interface

### ISSUE THREAD

**Issue by ZeFifi** [irtimmer/moonlight-embedded#288] opened 2016-01-04 12:19 UTC
Hi all,

I just installed Moonlight on my Raspberry Pi 2 (Raspbian). I'm using a Xbox One Wireless controller and it's works very well with Steam and with some (1/3 in fact) games. I have no control/sound/stream issues with Life is strange but when I want to play to "Ori and the blind forest" or "Splinter Cell Blacklist", the pad is not detected (but it's OK if I launch the game directly on my computer).

I read something about the rxinput.dll file from the C:\Program Files (x86)\NVIDIA Corporation\NvStreamSrv\ folders. I renamed it as .dll.old : despite a warning window from nVidia GeFore Experience, the game launches and the controller works... but I have no sound !

Did someone had the same issue and know how could I fix it :) ? 

Thanks a lot for you help !

**Comment by irtimmer** [comment] 2016-01-04 12:26
Duplicate of #171

**Closed by irtimmer** 2016-01-04 12:26 UTC
Labels: duplicate

**Comment by 7hunderbug** [comment] 2016-01-04 12:36
Is your Xbox controller connected to your PC or to your Raspberry Pi?

If connected to your Raspberry Pi, which driver are you using, xpad or xboxdrv?

If connected to your PC, moonlight might not work correctly as it expects your controller to be connected to the Pi, and all control signals passed via the gamestream protocol.

 

On Mon Jan 4 12:19:46 2016 GMT, ZeFifi wrote:
> Hi all,
> 
> I just installed Moonlight on my Raspberry Pi 2 (Raspbian) I'm using a Xbox One Wireless controller and it's works very well with Steam and with some (1/3 in fact) games I have no control/sound/stream issues with Life is strange but when I want to play to "Ori and the blind forest" or "Splinter Cell Blacklist", the pad is not detected (but it's OK if I launch the game directly on my computer)
> 
> I read something about the rxinputdll file from the C:\Program Files (x86)\NVIDIA Corporation\NvStreamSrv\ folders I renamed it as dllold : despite a warning window from nVidia GeFore Experience, the game launches and the controller works but I have no sound !
> 
> Did someone had the same issue and know how could I fix it :) ? 
> 
> Thanks a lot for you help !
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/irtimmer/moonlight-embedded/issues/28

-- 
Sent from my Jolla

**Comment by ZeFifi** [comment] 2016-01-04 12:52
Hi @irtimmer ,

Thanks for you reply. I've already read it before posting here but it's for Xbox 360 Wireless controller. I'm using the One one ;)

@7hunderbug Thanks ! My wireless receiver is connected to my computer, not to the Raspberry. I'm at work right now but I'm wondering something : would the pad work if it's wirelessly connected to the Pi ? Don't Steam expect the controller to be connected where it's hosted, meaning on the PC ?

Thanks again guys !

**Comment by 7hunderbug** [comment] 2016-01-04 13:00
Moonlight and the Nvidia gamestream protocol expect game control signals to originate from the client device, not the host PC, therefore it is preferrable to have your controller connected to your Rasperry Pi. I can't remember off hand whether moonlight has an option to force game control from the host side however, the previous statement stands.

**Comment by ZeFifi** [comment] 2016-01-04 13:03
Mmh OK ! Can't wait to try this tonight ! It would be so cool ! Do you know if the xpad or xboxdrv drivers are supposed to support the Xbox One Wireless gamepad ?

**Comment by 7hunderbug** [comment] 2016-01-04 13:17
http://pingus.seul.org/~grumbel/xboxdrv/

"Supported and tested devices
    Xbox1 controller, both official and third party
    Xbox360 USB controller
    Xbox360 wireless controller via the USB wireless receiver
    Xbox360 USB guitar and drum kit
    Thrustmaster Dual Power 3 Gamepad
    any joystick support by Linux via the evdev interface"

**Comment by ZeFifi** [comment] 2016-01-04 13:20
@7hunderbug Thanks a lot, if it works... :D ! I keep you posted !

**Comment by Kalagon** [comment] 2016-01-04 14:49
If you want to use controllers on your host PC you need to rename/remove the rximput.dll in both the Program Files and Program Files (x86) nvstrmsrv folders. After only removing one of them I also didn't get any audio on the Moonlight client.
You'll need to do this every time GeForce Experience is updated, but it shouldn't be too difficult to do this with a script.
The Problem is that many games like Rocket League etc. only accept one Controller in the menus, thus choosing the first one that pops up. The Nvidia server registers the remote controller from the client as a local controller. If this one pops up first you won't be able to control it with the controllers that are actually connected locally.
Setting up the controller on the Pi should work but can be tiresome if it doesn't work as expected.

**Comment by ZeFifi** [comment] 2016-01-04 14:50
Thanks for your reply @Kalagon ! I didn't know this file was in 2 folders ! I'll check this out tonight and will keep you posted !

**Comment by ZeFifi** [comment] 2016-01-05 08:34
@Kalagon @7hunderbug  Thanks a lot for the tips, it worked ! :)

**Comment by Direcka** [comment] 2016-10-19 16:13
Renaming both DLL files is not working for me. Have someone same problem or any workaround?

**Comment by Xiller** [comment] 2016-10-29 18:33
Hi Direcka, same here, i think it is a new bug since GFE 3.1. 

i tryed to rename the files here too: 
C:\ProgramData\NVIDIA Corporation\GeForce Experience\Update\GFExperience.NvStreamSrv\x86\server
C:\Users\All Users\NVIDIA Corporation\GeForce Experience\Update\GFExperience.NvStreamSrv\amd64\server

but doesnt work either :(

**Comment by heydude1337** [comment] 2016-10-30 16:21
For me it didnt work either. But renaming the rxinputgamepad.dll in both folders did the trick :)
