### ISSUE TITLE
Audio stuttering - some possible solutions

### ISSUE THREAD

**Issue by JontyNewman** [irtimmer/moonlight-embedded#211] opened 2015-08-30 20:11 UTC
I managed to set up moonlight on my RPi today and I now have it working almost perfectly. One of the main hurdles I had to overcome was audio stuttering. Just thought I'd post this in case it helps others fix the problem and possibly help contributers find the cause.

This is my setup:
```
 PC --{Ethernet}-- Powerline Adaptor ---.
                                        |
.---------{Electrical Circuit}----------`
|
`---- Powerline Adaptor --{Ethernet}----.
                                        |
 RPi ---------{Ethernet}--- Router ----`
```

Here's a list of things I tried that did **_not_** seem to solve audio stuttering: 
* Compiling from source ([release 2.1.1](https://github.com/irtimmer/moonlight-embedded/releases/tag/v2.1.1))
* Using an [archived binary](http://archive.itimmer.nl/archlinux/moonlight/os/)
* Lowering resolution / framerate / bitrate / packet size
* Removing all external devices (i.e. keyboard / Xbox 360 Wireless Receiver / Xbox 360 Wireless Controller via Plug & Play cable)
* Configuring `Powerline Adaptor` for prioritised audio and video Quality of Service (TL-PA411KIT)

And here are the solutions I found:
* Bypass the `Powerline Adaptor` and go direct to the `Router` (see above)
* Manually install [moonlight](http://archive.itimmer.nl/archlinux/moonlight/os/armv6h) and [dependencies](http://eu.mirror.archlinuxarm.org/armv6h/extra/) on a clean, unupgraded [ArchLinux image](http://downloads.raspberrypi.org/arch/images/arch-2014-06-22/)

After successfully resolving the stuttering with a clean install, I was able to replicate the issue by launching moonlight with a keyboard, Xbox 360 Wireless Receiver and Plug & Play cable connected, and then disconnecting the keyboard once the stream was established.

Hope this helps!

Many thanks,

Jonty

**Comment by irtimmer** [comment] 2016-01-01 16:13
Duplicate of #126

**Closed by irtimmer** 2016-01-01 16:13 UTC
