### ISSUE TITLE
Xbox 360 Controller

### ISSUE THREAD

**Issue by RogerDom** [irtimmer/moonlight-embedded#516] opened 2017-06-19 19:17 UTC
I've followed everything i can find online, when trying to map the buttons using Moonlight map it says cant connect to the server. 

Found this in the config but even after i set it to  (moonlight stream -mapping
/usr/share/moonlight/gamecontrollerdb.txt 192.168.1.74) 

(## Default used mapping for streaming
(## Searched for in $XDG_DATA_DIRS/moonlight or /usr/share/moonlight and /usr/local/share/moonlight)
(## Mapping can also be user overrided in $XDG_CONFIG_DIR/moonlight or ~/.config/moonlight or current directory)
(#mapping = gamecontrollerdb.txt)

but that has made no difference. The controller and Pi both work fine.

Tried this but i didnt get where you change the id
_Hi @gabrielpiccolo4, I found there is a configuration file /usr/share/moonlight/gamecontrollerdb.txt with all devices ids and configurations. Maybe your controller isn't there.
I have added mine by copying a similar one (Generic X-Box) at the end of the file and changing the id. You may read the id at file /proc/bus/input/devices ('I' field) and adding four zeros at the end of each parameter.
{Bus}0000{Vendor}0000{Product}0000{Version}0000.
I hope this help you to get your controller working again._

this is my /proc/bus/input/devices and gamecontrollerdb.txt has Xbox Gamepad (userspace driver) in it

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="Xbox Gamepad (userspace driver)"
P: Phys=
S: Sysfs=/devices/virtual/input/input2
U: Uniq=
H: Handlers=js1 event2
B: PROP=0
B: EV=b
B: KEY=7fdb0000 0 0 0 0 0 0 0 0 0
B: ABS=3001b

Please provide the following info.

**_NVidia Geforce Experience version:_**
The latest
**Moonlight Embedded version:**
The latest
**Moonlight Embedded source:** _repository/included in distribution/compiled from source/..._
**Moonlight Embedded running on:** _Raspberry Pi/Cubox-i/Hummingboard/Other linux device/..._
**Moonlight Embedded running on distribution:** _Arch Linux/Raspbian/OpenELEC/..._

**Verbose output `-verbose` of Moonlight Embedded:**
no idea what this is

**What is the expected result?**
Mapped Xbox360 Wired control's

**What happens instead of that?**
Steam picks up that its got a controller plugged in but none of the controls work

**Comment by irtimmer** [comment] 2017-06-19 20:32
Duplicate of #514

**Closed by irtimmer** 2017-06-19 20:32 UTC
