### ISSUE TITLE
Can't map Wired Xbox 360 Controller from gamecontrollerdb.txt

### ISSUE THREAD

**Issue by arunankogulan** [irtimmer/moonlight-embedded#677] opened 2018-07-31 17:22 UTC
Please provide the following info.

**_NVidia Geforce Experience version:_** 3.14.1.48
**Moonlight Embedded version:** 2.4.6
**Moonlight Embedded source:** TechWizTime script
**Moonlight Embedded running on:** Raspberry Pi
**Moonlight Embedded running on distribution:** Retropie

**Verbose output `-verbose` of Moonlight Embedded:**
pi@retropie:~ $ moonlight stream -verbose
Moonlight Embedded 2.4.6 (PI;ALSA;EMBEDDED)
Searching for server...
Connect to 192.168.1.64...
NVIDIA GeForce GTX 970, GFE 3.14.1.48 (gs_04_08_24506279, 7.1.408.0)
Platform Raspberry Pi (Broadcom)
Loading mappingfile /usr/share/moonlight/gamecontrollerdb.txt
Can't map (dpdown:+a1)
Can't map (dpleft:-a0)
Can't map (dpright:+a0)
Can't map (dpup:-a1)
Can't map (dpdown:+a1)
Can't map (dpleft:-a0)
Can't map (dpright:+a0)
Can't map (dpup:-a1)
Can't map (dpdown:+a1)
Can't map (dpleft:-a0)
Can't map (dpright:+a0)
Can't map (dpup:-a1)
Can't map (dpdown:+a1)
Can't map (dpleft:-a0)
Can't map (dpright:+a0)
Can't map (dpup:-a1)
Can't map (lefttrigger:+a3)
Can't map (righttrigger:-a3)
Can't map (dpdown:+a1)
Can't map (dpleft:-a0)
Can't map (dpright:+a0)
Can't map (dpup:-a1)
Can't map (dpdown:+a1)
Can't map (dpleft:-a0)
Can't map (dpright:+a0)
Can't map (dpup:-a1)
Detected Microsoft X-Box 360 pad (030000005e0400008e02000014010000) on /dev/input/event1 as X360 Controller
Stream 1280 x 720, 60 fps, 10000 kbps
Initializing platform...done
Resolving host name...done
Starting RTSP handshake...done
Initializing control stream...done
Initializing video stream...done
Initializing audio stream...done
Initializing input stream...done
Starting control stream...done
Starting video stream...done
Starting audio stream...done
Starting input stream...done
Unrecoverable frame 141: 11+0=11 received < 16 needed
Network dropped an entire frame
Waiting for IDR frame
IDR frame request sent
Waiting for IDR frame
Waiting for IDR frame
Returning RTP packet queued for too long
Received OOS audio data (expected 55339, but got 55460)
Control stream received disconnect event
Loss Stats: Transaction failed: 11
Stopping input stream...done
Stopping audio stream...done
Stopping video stream...done
Stopping control stream...done
Cleaning up input stream...done
Cleaning up audio stream...done
Cleaning up video stream...done
Cleaning up control stream...done
Cleaning up platform...done

**What is the expected result?**
Game/Big Picture loads in and is fully controllable with Xbox 360 controller
**What happens instead of that?**
Game/SBP loads, but is only controllable with Keyboard and/or Mouse. The controller provides no input

**Comment by maxtimix** [comment] 2018-08-02 01:28
same here. Monday the controller was working fine.

sudo  moonlight stream -verbose
Moonlight Embedded 2.4.6 (PI;ALSA;EMBEDDED)
Searching for server...
Connect to 192.168.1.50...
NVIDIA GeForce GTX 980, GFE 3.14.1.48 (gs_04_08_24506279, 7.1.408.0)
Platform Raspberry Pi (Broadcom)
Loading mappingfile /usr/share/moonlight/gamecontrollerdb.txt
Detected Microsoft X-Box 360 pad (030000005e0400008e02000014010000) on /dev/input/event3 as X360 Controller
Stream 1280 x 720, 60 fps, 10000 kbps
Initializing platform...done
Resolving host name...done
Starting RTSP handshake...done
Initializing control stream...done
Initializing video stream...done
Initializing audio stream...done
Initializing input stream...done
Starting control stream...done
Starting video stream...done
Starting audio stream...done
Starting input stream...done
Removed input device
Detected Microsoft X-Box 360 pad (030000005e0400008e02000014010000) on /dev/input/event3 as X360 Controller
Detected Microsoft X-Box 360 pad (030000005e0400008e02000014010000) on /dev/input/event4 as X360 Controller

**Comment by maxtimix** [comment] 2018-08-02 03:07
OK it's working now! It seems the issue is with the version 3.14.148 Nvidia Experience. I downgraded to 4.13.1.30, plug/unplug the controller in the PC and connect it to the Pi. Steam BP/game should detected your controller.

**Closed** 2018-08-02 09:45 UTC
