### ISSUE TITLE
RTSP DESCRIBE request failed:500 

### ISSUE THREAD

**Issue by scoobyd00** [irtimmer/moonlight-embedded#191] opened 2015-08-15 15:02 UTC
Ok, ive gone for a new Windows 10 install .

Ive succesfully paired moonlight but when i come to run the stream i get the following error message.

Starting RTSP handshake...RTSP DESCRIBE request failed:500 
failed: -1

Ive disabled windows firewall, got static ip addresses for both my raspberry pi and pc but i still cant get the stream to work.

It worked fine in windows 8.1

Any ideas its driving me crazy.

**Comment by Ilos** [comment] 2015-08-15 15:07
try to reinstall your drivers and Geforce Experience.

**Comment by irtimmer** [comment] 2015-08-15 15:09
Duplicate of #180

**Closed by irtimmer** 2015-08-15 15:09 UTC
Labels: duplicate

**Comment by scoobyd00** [comment] 2015-08-15 15:26
Still getting the Starting RTSP handshake...RTSP DESCRIBE request failed:500 
failed: -1 error
Tried re installing drivers and experience but the stream wont start. Pairing is fine.

Anyone know what the error 500 means?.
