### ISSUE TITLE
Connected directly through eth0 on Pi 3, still terminates stream

### ISSUE THREAD

**Issue by firepro20** [irtimmer/moonlight-embedded#390] opened 2016-06-25 22:04 UTC
Moonlight Embedded 2.2.0 (EMBEDDED;PI)
Connect to 192.168.0.13...
NVIDIA GeForce GTX 970, GFE 2.11.4.0 (protocol version 7)
Stream 1280 x 720, 60 fps, 10000 kbps
Initializing platform...done
Resolving host name...done
Starting RTSP handshake...done
Initializing control stream...done
Initializing video stream...done
Initializing audio stream...done
Initializing input stream...done
Starting control stream...done
Starting video stream...done
Starting audio stream...done
Starting input stream...done
Control stream received disconnect event
Loss Stats: Transaction failed: 11
Stopping input stream...done
Stopping audio stream...done
Stopping video stream...done
Stopping control stream...done
Cleaning up input stream...done
Cleaning up audio stream...done
Cleaning up video stream...done
Cleaning up control stream...done
Terminating RTSP handshake...done
Cleaning up platform...done

**_NVidia Geforce Experience version:_*2.11.4.0*
**Moonlight Embedded version:*2.2*
**Moonlight Embedded running on:*Raspberry Pi 3*

**Output of Moonlight Embedded:**

720p stream @60fps, after couple of seconds it stops

**What is the expected result?**

uninterrupted stream

**What happens instead of that?**

Interrupted stream by error:
 
'Control stream received disconnect event
Loss Stats: Transaction failed: 11'

**Comment by irtimmer** [comment] 2016-06-25 22:21
Duplicate of #368

**Closed by irtimmer** 2016-06-25 22:21 UTC
