### ISSUE TITLE
[Bug] Cannot build moonlight-embedded for Rock64 running DietPi

### ISSUE THREAD

**Issue by Sk1pp3r** [irtimmer/moonlight-embedded#685] opened 2018-08-29 11:05 UTC
I've tried installing moonlight-embedded on Rock64, but I'm stuck on cmake operation. Is this some kind of OS issue, or it's the device itself?

**Moonlight Embedded running on:** _Rock64_
**Moonlight Embedded running on distribution:** _DietPi with MATE desktop_

**What is the expected result?**
Compilation succeeds

**What happens instead of that?**
Compilation fails.

Below is the output of terminal:
```
rock64@rock64:~/Software/moonlight-embedded/build# cmake ../
-- Could NOT find Broadcom (missing:  BROADCOM_INCLUDE_DIR VCOS_LIBRARY VCHIQ_LIBRARY OPENMAXIL_LIBRARY BCM_HOST_LIBRARY)
-- Could NOT find Freescale (missing:  FREESCALE_INCLUDE_DIR KERNEL_INCLUDE_DIR VPU_LIBRARY)
-- Could NOT find Amlogic (missing:  AMLOGIC_INCLUDE_DIR AMCODEC_LIBRARY AMADEC_LIBRARY AMAVUTILS_LIBRARY)
-- Could NOT find Rockchip (missing:  ROCKCHIP_INCLUDE_DIR ROCKCHIP_LIBRARY)
-- Checking for module 'sdl2>=2.0.4'
--
-- Checking for module 'libavcodec'
--   No package 'libavcodec' found
-- Checking for module 'libavutil'
--   No package 'libavutil' found
-- Checking for module 'x11'
--   No package 'x11' found
-- Checking for module 'vdpau'
--   No package 'vdpau' found
-- Checking for module 'libva'
--   No package 'libva' found
-- Checking for module 'libva-x11'
--   No package 'libva-x11' found
-- Checking for module 'libcec>=4'
--
-- Checking for module 'egl'
--   No package 'egl' found
-- Checking for module 'glesv2'
--   No package 'glesv2' found
CMake Error at CMakeLists.txt:166 (message):
  No video output available


-- Configuring incomplete, errors occurred!
See also "/root/Software/moonlight-embedded/build/CMakeFiles/CMakeOutput.log".
See also "/root/Software/moonlight-embedded/build/CMakeFiles/CMakeError.log".
```

**Comment by irtimmer** [comment] 2018-08-29 11:11
Duplicate of #654

**Closed by irtimmer** 2018-08-29 11:11 UTC
