### ISSUE TITLE
Multiple Controllers in RetroPie Moonlight

### ISSUE THREAD

**Issue by DasMork** [irtimmer/moonlight-embedded#474] opened 2017-02-18 18:19 UTC
Hey Guys I need some help,

So I got my RaspberryPi 3 last Week and set up RetroPie succesfully and then Moonlight in RetroPie like in this Video: https://www.youtube.com/watch?v=pYoLOoBkEnU

I tried mapping every single Controller to another file and write all the mapping files into the sh file but then only the last written controller works, the rest is only able to use the left analog stick. If i map none of them in the sh file all work but some keys are wrong...

Can anybody help me ? My GFE and RetroPie are both on the newest Version and im using a real Xbox360 Controller, a fake xbox 360 controllr and a ps3 controller.

I can map any of these as the only controller and then they all work fine as long as their are no other controllers..

Sorry for my bad english and thanks for your help!

Greetings DasMork

**Comment by theFisher86** [comment] 2017-02-22 15:26
This is a duplicate of [issue 468](https://github.com/irtimmer/moonlight-embedded/issues/468)

**Closed** 2017-02-22 18:50 UTC
Labels: duplicate
