### ISSUE TITLE
Audio Stuttering on Pi2+

### ISSUE THREAD

**Issue by samusaran** [irtimmer/moonlight-embedded#222] opened 2015-10-13 15:33 UTC
Hi. Like many users before me, I have some kind of audio stuttering while streaming. I will describe it as better I can.

My PC specs:
Intel Core i5 4670 @4.00
8GB Ram
Zotac GTX 970

Raspberry Pi 2+
Everything updated as 13 Oct. 2015
Xbox 360 Wired Controller
Logitech K400

This is the command line i use to start moonlight:
`moonlight stream 192.168.0.100 -1080 -60fps -map x360.map -app Steam`

PC is hooked up on ethernet, while the Pi is hooked up on ethernet by powerlines.
I did bandwidth test on both of them and they use all bandwidth possible (gigabit for PC, 100mbit for Pi)

- The audio stuttering appears on every quality combination from 720p@30 to 1080p@60, and it doesn't change magnitude.
- I have errors in the console in both low and high quality, but different from each other.
- At 720p@30 mostly of the errors are `Alsa error from writei: -11`
- At 1080p@60 mostly of the errors are a repeated sequence of: `Discarding RTP packet queued for too long`, `Received OOS audio data` (usually with a difference of 2-3 frames) and  `Opus decode error: -1`.
- each of the following parameters does not change the behaviour at all: `-packetsize` `-bandwidth` `-remote` `-localaudio` `-packetsize` `-nosops`

Looked with htop and nethogs, the network has very low traffic (3kb/s sent, 1-2kb/s received from pc), and the Pi is not under heavy load (20%-ish load, 200mb ram).

Also I'm NOT logged on X. CLI only. Never actually tried launching moonlight from GUI, but I guess it cannot perform better.

**Comment by irtimmer** [comment] 2016-01-01 16:13
Duplicate of #126

**Closed by irtimmer** 2016-01-01 16:13 UTC
