### ISSUE TITLE
Buster package not available.

### ISSUE THREAD

**Issue by greigs** [irtimmer/moonlight-embedded#768] opened 2019-11-24 14:26 UTC
I was hoping to install the package for buster but it isn't available here - http://archive.itimmer.nl/raspbian/moonlight/dists/

**Comment by discordianfish** [comment] 2019-11-27 11:20
@irtimmer Is the tooling to build the debian packages included in this repo somewhere? If so, I could look into building a buster package but would rather not start from scratch :)

**Comment by irtimmer** [comment] 2019-11-30 16:49
Duplicate of #750

**Closed by irtimmer** 2019-11-30 16:49 UTC
Labels: duplicate
