### ISSUE TITLE
Platform 'default' not found

### ISSUE THREAD

**Issue by miroky** [irtimmer/moonlight-embedded#193] opened 2015-08-15 16:22 UTC
Hi there!

I just install this software on a Raspberry Pi 2 (Raspbian) following this instructions:

- sudo nano /etc/apt/sources.list (writting it...)
- apt-get update
- apt-get install moonlight-embedded

When i try to do any kind of command, EXCEPT 'moonlight' or 'moonlight help', i got an error:

Platform 'default' not found.
Screenshot: http://i.imgur.com/HMhc1ai.png

Could you help me?

Thanks

**Comment by irtimmer** [comment] 2015-08-15 16:44
Duplicate of #190

**Closed by irtimmer** 2015-08-15 16:44 UTC
Labels: duplicate

**Comment by cgutman** [comment] 2015-08-15 18:35
@miroky The fix is here - https://github.com/irtimmer/moonlight-embedded/issues/192#issuecomment-131422208
