### ISSUE TITLE
Raspbian (debian 9 with noobs install) installation failed (broken package)

### ISSUE THREAD

**Issue by Tsuna77** [irtimmer/moonlight-embedded#549] opened 2017-08-28 09:33 UTC
Please provide the following info.

**Moonlight Embedded version:** _Latest in jessie repo (strectch repo not available)_
![capture9](https://user-images.githubusercontent.com/3943654/29767786-0aee420c-8be4-11e7-9c03-bb122230fc7b.PNG)

**Moonlight Embedded source:** _http://archive.itimmer.nl/raspbian/moonlight_
**Moonlight Embedded running on:** _Raspberry Pi 3 type B_
**Moonlight Embedded running on distribution:** _Raspbian_
![capture7](https://user-images.githubusercontent.com/3943654/29767643-862c2fca-8be3-11e7-9c32-0774516a2205.PNG)

**Verbose output `-verbose` of Moonlight Embedded:** Nothing

**What is the expected result?**
Install successfull

**What happens instead of that?**
Could not install, broken libssl1.0.0 package not available (libssl1.0.2 & libssl1.1 installed)
![capture10](https://user-images.githubusercontent.com/3943654/29767942-a8952994-8be4-11e7-90ea-562caed7f641.PNG)
![capture8](https://user-images.githubusercontent.com/3943654/29767690-b49c1370-8be3-11e7-96b7-4775b2b81996.PNG)

**Comment by MatWan67** [comment] 2017-08-28 17:30
I m experiencing the same issue

**Comment by kittenslut** [comment] 2017-08-30 19:50
Same issue, sadly.

**Comment by Kohtachan** [comment] 2017-08-31 22:22
Same Problem with raspbian stretch.

**Comment by Unorthodactyl** [comment] 2017-09-01 00:06
You can download and install libssl1.0.0 from here https://packages.debian.org/jessie/armhf/libssl1.0.0/download
this will let you install moonlight-embedded as per the wiki's package instructions
then you will have to use sudo to pair and stream.

**Comment by Unorthodactyl** [comment] 2017-09-01 00:09
Maybe don't close this issue so others can see this, also this is a workaround and the issue is still with the project.

**Comment by cgutman** [comment] 2017-09-01 00:31
It should be pretty simple for @irtimmer to compile a package for Stretch. Now that Stretch is using OpenSSL 1.1 like Arch, master should build stock without needing a special branch for the ancient OpenSSL in Jessie.

**Comment by benwilesmusic** [comment] 2017-09-29 13:58
I posted a solution here: #568

**Comment by irtimmer** [comment] 2017-11-07 20:52
Since version 2.4.4 a package for Raspbian Stretch is provided

**Closed by irtimmer** 2017-11-07 20:52 UTC
