### ISSUE TITLE
official moonlight discord

### ISSUE THREAD

**Issue by RobinNyan** [irtimmer/moonlight-embedded#694] opened 2018-09-28 12:25 UTC
Hello Iwan and other embedded contributors! 

I'm Robin, the non-official head of the official discord community! We have channels for each moonlight version, even for the embedded version and new people visit us every day, searching for help, even cameron gutman and the whole original crew is on the discord. Since there are many problems people have with the embedded version and we have NO embedded dev on the server, I'm here to ask you if you want to join the official moonlight discord (it's even linked on the moonlight website, check it out)

here's the link: https://discord.gg/5UUyqxv

I'm sure the original team would appreciate if any embedded dev joins the discord server since it would help us a lot help the community. We have 500 members right now and we keep growing every day. Thanks for taking your time reading through this and have a nice day :)

**Comment by irtimmer** [comment] 2018-09-28 12:37
Duplicate of #678

**Closed by irtimmer** 2018-09-28 12:37 UTC
Labels: duplicate, missing required information, non-reproducible, not a bug

**Comment by RobinNyan** [comment] 2018-09-28 12:40
indeed a duplicate, but there are more and more requests for embedded issues and cameron is the only one around who helps them. I don't see why you don't want to help, since you obviously love the moonlight project. the discord is a part of the moonlight project now and we have more and more devs around helping the users and fixing stuff. we'd all appreciate it if you join us.
