### ISSUE TITLE
Can't launch steam game through Moonlight

### ISSUE THREAD

**Issue by Bastbog** [irtimmer/moonlight-embedded#471] opened 2017-02-10 22:35 UTC
Please provide the following info.

**_NVidia Geforce Experience version:_**3.3.0.95
**Moonlight Embedded running on:** Raspberry pi 3

I have an issue where i can't start any steam game.
Big picture boots up just fine, but any game just gets me a splash screen and back to big picture.

The weird thing is i can start watch dogs 2 through steam that goes through uplay.
Any ideas?

**Comment by irtimmer** [comment] 2017-02-11 10:22
Duplicate of #394

**Closed by irtimmer** 2017-02-11 10:22 UTC
