### ISSUE TITLE
Moonlight on Retropie won't display fullscreen

### ISSUE THREAD

**Issue by nareau** [irtimmer/moonlight-embedded#478] opened 2017-03-02 20:04 UTC
**_NVidia Geforce Experience version:_**
3.4.0.70

**Moonlight Embedded version:**
2.2.2

**Moonlight Embedded running on:**
Raspberry Pi 3, Retropie

**What is the expected result?**
I expect steam to fill the screen.

**What happens instead of that?**
Only the middle 2/3rds of the screen are filled. Black bars with white text can be seen "behind" the Moonlight stream at the top and bottom of the TV. Both my PC's monitor, and my TV are natively 1920x1080.

This is the command I'm running to start Moonlight:
moonlight stream -1080 -30fps  -mapping /opt/retropie/configs/moonlight/controller.map 10.0.0.10

![image](https://cloud.githubusercontent.com/assets/8355673/23524357/3c44c268-ff58-11e6-90e4-ca55aeebdfad.png)

I've tried changing the resolution on my monitor, and the resolution within Steam. I've also tried adding  **-height 1080** to the command. Nothing seems to have any effect. I've tried on another 1080p display, and got the same thing. I was able to get fullscreen working out of the box when I had it connected to a 7" touchscreen.

**Comment by Laephis** [comment] 2017-03-04 14:27
I'm having the same problem.  I've been using Moonlight on Retropie on and off for a while and I want to say this problem popped up a few months ago.  Just getting around to trying to fix it..

**Comment by brainfrz82** [comment] 2017-03-12 20:02
Same issue here, ive been trying some remote desktop apps for the rpi 3 to connect to my pc. At first, up until a few hours ago moonlight was working fine. After settling for moonlight i decided to uninstall all the other remote desktop apps i tried. Nomachine, freerdp and vnc client were uninstalled. After a reboot moonlight stopped working full screen. I havent been able to replicate the original working setting, even after reinstalling all the other tools.

**Comment by irtimmer** [comment] 2017-03-18 19:13
It looks like the aspect ratio is incorrectly set or detected on the Raspberry Pi. But it looks like there are some functions to change the aspect ratio in code so maybe I will add them in the next release.

**Comment by Black4Key** [comment] 2017-04-01 17:51
Same problem for me, but neither the windows control panel nor nvidia control panel work for me, every time the stream start it adjust itself as it want.
(I'm using moonlight embedded version 2.3.0 on a rasperry pi 3 model B+ with raspbian as OS)

**Comment by tbergeron** [comment] 2017-04-13 22:20
Currently having the same problem. Same config as the fellow commenter above me ^^

**Comment by alfalfa1978** [comment] 2017-04-16 18:20
Fullscreen works fine for me on RPi 3 with RetroPie.
@tbergeron The scaling mode in my NV control panel is still set to "aspect ratio", but I got no problems with fullscreen.

I've only got a problem using CEMU (WiiU Emulator) - in fullscreen mode the screen freezes while streaming (emulator still running), but if you switch to the emulator's windowed mode, it works until you switch back to fullscreen.
Several people have the problem but nobody knows if it's a problem of CEMU or Moonlight Embedded.

**Comment by cgutman** [comment] 2017-04-16 22:12
@alfalfa1978 It's neither CEMU or Moonlight's problem. Nvidia's frame buffer capture doesn't correctly handle certain full-screen rendering methods. If one of these applications is the only visible window, the display won't update. Chrome, Edge, and some other UWP apps have this issue when displaying video in full-screen. This is the first I've heard of a game triggering it, but it doesn't really surprise me.

**Comment by alfalfa1978** [comment] 2017-04-16 23:47
Thank you for your explanation!
I hope this will by fixed anyhow.
 
Here’s the link to the regarding reddit thread:
https://www.reddit.com/r/cemu/comments/5qayto/issue_with_moonlight_and_nvidia_gamestream/
 
Greetings from Berlin
Thomas
 
Von: Cameron Gutman [mailto:notifications@github.com] 
Gesendet: Montag, 17. April 2017 00:12
An: irtimmer/moonlight-embedded
Cc: alfalfa1978; Mention
Betreff: Re: [irtimmer/moonlight-embedded] Moonlight on Retropie won't display fullscreen (#478)
 
@alfalfa1978 <https://github.com/alfalfa1978>  It's neither CEMU or Moonlight's problem. Nvidia's frame buffer capture doesn't correctly handle certain full-screen rendering methods. If one of these applications is the only visible window, the display won't update. Chrome, Edge, and some other UWP apps have this issue when displaying video in full-screen. This is the first I've heard of a game triggering it, but it doesn't really surprise me.

**Comment by alfalfa1978** [comment] 2017-04-17 00:24
Hey Cameron,
 
A reddit user just posted:
https://www.reddit.com/r/cemu/comments/5qayto/issue_with_moonlight_and_nvidia_gamestream/dgcik54/
 
It works fine for me!
Perhaps it also fixes other full-screen issues.
 
Von: Cameron Gutman [mailto:notifications@github.com] 
Gesendet: Montag, 17. April 2017 00:12
An: irtimmer/moonlight-embedded
Cc: alfalfa1978; Mention
Betreff: Re: [irtimmer/moonlight-embedded] Moonlight on Retropie won't display fullscreen (#478)
 
@alfalfa1978 <https://github.com/alfalfa1978>  It's neither CEMU or Moonlight's problem. Nvidia's frame buffer capture doesn't correctly handle certain full-screen rendering methods. If one of these applications is the only visible window, the display won't update. Chrome, Edge, and some other UWP apps have this issue when displaying video in full-screen. This is the first I've heard of a game triggering it, but it doesn't really surprise me.

**Comment by irtimmer** [comment] 2017-05-27 15:20
Duplicate of #364

**Closed by irtimmer** 2017-05-27 15:20 UTC
