### ISSUE TITLE
Steam Big Picture > Games crash...

### ISSUE THREAD

**Issue by Sendoushi** [irtimmer/moonlight-embedded#248] opened 2015-11-22 20:57 UTC
Hi,

Streaming the Steam Big Picture Mode works well. I play "most" of the games well but there are others that crash.

So, from my library, the games that I know that crash:
```
Borderlands 2    # After starting game and initial story
Spelunky         # On enter
```

**Comment by H3llsing** [comment] 2015-12-13 13:35
i have the same problem with this game.
Already tried to start via Steam, without Steam (direct call in gameslist with moonlight).
starting on the pc without streaming works well. i also tried to connect one gamepad to the pc but still crashes when streaming.

`Magicka      # After starting`

**Comment by havnar** [comment] 2016-02-08 18:25
I have the same problem with most games that I've tried so far.
Can get into big picture mode but there it dies.

**Comment by cgutman** [comment] 2016-02-08 23:29
There's a bug that will need to be addressed with a GFE update.

https://forums.geforce.com/default/topic/909598/gamestream/gamestream-broken-with-steam-and-big-picture-mode/

**Comment by irtimmer** [comment] 2016-02-09 12:40
Duplicate of #292

**Closed by irtimmer** 2016-02-09 12:40 UTC
