### ISSUE TITLE
libenet1a but it is not installable

### ISSUE THREAD

**Issue by PartyUnicorn** [irtimmer/moonlight-embedded#396] opened 2016-07-07 20:45 UTC
**Moonlight Embedded running on:** _Raspberry Pi
Hey im preety new to linux and stuff, but when i try to download the packages(sudo apt-get install moonlight-embedded) i get this error
"The following packages have unmet dependencies:
 moonlight-embedded : Depends: libenet1a but it is not installable
E: Unable to correct problems, you have held broken packages.
"
i even did reinstall debian in my raspberry. 
can someone help me?

**Comment by irtimmer** [comment] 2016-07-07 22:20
Duplicate of #355

**Closed by irtimmer** 2016-07-07 22:20 UTC

**Comment by PartyUnicorn** [comment] 2016-07-07 22:24
Thanks buddy i didnot found it!
