### ISSUE TITLE
Wrong screen size

### ISSUE THREAD

**Issue by xtrem007** [irtimmer/moonlight-embedded#281] opened 2015-12-30 20:12 UTC
When I start Steam with -720 or -1080 on HDTV it's no longer fit full screen. There are bars on the left and right side of the screen and I can see terminal output on left side.

**Comment by Sardtok** [comment] 2015-12-31 18:31
This happens to me too in 1366x768 mode (native resolution of the connected screen). Running with -width 1366 -height 768.

**Comment by KillerXtreme-** [comment] 2016-01-05 21:36
I as well am having this issue. It seems to have happened to me after updating GFE.

**Comment by irtimmer** [comment] 2016-04-03 16:52
Duplicate of #276

**Closed by irtimmer** 2016-04-03 16:52 UTC
Labels: duplicate
