### ISSUE TITLE
Control stream sent disconnect event after one minute

### ISSUE THREAD

**Issue by firepro20** [irtimmer/moonlight-embedded#387] opened 2016-06-19 10:55 UTC
**_NVidia Geforce Experience version:_** 2.11.3.5
**Moonlight Embedded version:** 2.2.0
**Moonlight Embedded running on:** Raspberry Pi 3

**Output of Moonlight Embedded:**

Normal lag free output stops after approximately a minute with error Transaction 11 Loss state and 
Control stream sent disconnect event after one minute. Not sure if the GFE server is the problem or the PI. I am running the command with *moonlight stream MY IP* replacing MY IP with actual GFE Server IP. 

The setup I have is the Pi connected with a repeater using ethernet cable and the repeater connecting wirelessly with a router upstairs. Manually decreasing the bitrate and resolution did not stop it from ending the stream. What can I do?

**What is the expected result?**
Uninterrupted stream
**What happens instead of that?**
Interrupted stream, stream stops after a minute or so with the above error

**Comment by irtimmer** [comment] 2016-06-28 21:45
Duplicate of #368

**Closed by irtimmer** 2016-06-28 21:45 UTC
