### ISSUE TITLE
Libnetla Failure

### ISSUE THREAD

**Issue by cmz1675** [irtimmer/moonlight-embedded#361] opened 2016-04-10 22:31 UTC
**_NVidia Geforce Experience version:**2.11.2.65
**Moonlight Embedded version:**Download Failure of Latest Version as of 4/10/16 
**Moonlight Embedded Is Running On:** Raspberry Pi

**Output of Moonlight Embedded:**
ri@raspberrypi: sudo apt-get install moonlight-embedded
Reading Package Lists...Done
Building Dependency Tree
Reading State Information.. Done
Some Packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable 
distribution that some required packages have not yet been created or been moved out of
Incoming.
The Following information may help resolve the situation;

The following packages have unmet dependencies:
   moonlight-embedded : Depends: libnetla but it is not installable 
E: Unable to correct problems, you have held broken packages 

**What is the expected result?**
Moonlight Doesn't install
**What happens instead of that?**
Nothing

**I ended up un-installing the old version fully to get the new working version. This error was caused on the reinstall part.**

**Comment by irtimmer** [comment] 2016-04-11 17:43
Duplicate of #355

**Closed by irtimmer** 2016-04-11 17:43 UTC
Labels: duplicate
