### ISSUE TITLE
Not Streaming  stuck on RTSP handshake

### ISSUE THREAD

**Issue by Athanaetos** [irtimmer/moonlight-embedded#279] opened 2015-12-24 16:24 UTC
From the title, I can't seem to stream. It might be that my Geforce Experience is version 2.9+ or something else. Please help, I really want to try this.

**Comment by HarryLovesCode** [comment] 2015-12-28 16:28
@Athanaetos Currently I'm on the Geforce Experience beta and I'm not having any hiccups. However, I encountered a similar issue when using a Xbox 360 controller with XPad. Black listing XPad and switching to XboxDrv fixed the problem, but I'm not sure if that is relevant to your issue.

**Comment by irtimmer** [comment] 2016-01-01 16:10
Duplicate of #274

**Closed by irtimmer** 2016-01-01 16:10 UTC
