### ISSUE TITLE
missing libcurl3 but only 4 is available

### ISSUE THREAD

**Issue by leee8675** [irtimmer/moonlight-embedded#767] opened 2019-11-14 03:57 UTC
Please provide the following info.

**_NVidia Geforce Experience version:_** 3.20.1.57
**Moonlight Embedded version:** not sure, have not been able to install it
**Moonlight Embedded source:** deb http://archive.itimmer.nl/raspbian/moonlight stretch main
**Moonlight Embedded running on:** _Raspberry Pi
**Moonlight Embedded running on distribution:** Raspbian_

**Verbose output `-verbose` of Moonlight Embedded:** N/A

**What is the expected result?** Installing Moonlight

**What happens instead of that?** I cannot install this program without libcurl3 unless there is a new version of this that I can get.

![error](https://user-images.githubusercontent.com/57739856/68825680-9b477500-0660-11ea-8341-ddc21859ab07.png)
![error2](https://user-images.githubusercontent.com/57739856/68825682-9d113880-0660-11ea-9f31-d124986a0ef5.png)

**Comment by LupusVII** [comment] 2019-11-20 11:54
Hi ! 
I add some troubles with this message but I manage to make my way by following this thread : https://github.com/irtimmer/moonlight-embedded/issues/716
Remove libcurl3 from the list of dependancies to fetch since it provokes errors.

**Comment by irtimmer** [comment] 2019-11-30 16:50
Duplicate of #750

**Closed by irtimmer** 2019-11-30 16:50 UTC
