### ISSUE TITLE
Moonlight no longer streaming after geforce update

### ISSUE THREAD

**Issue by shadowzero26** [irtimmer/moonlight-embedded#558] opened 2017-09-07 16:17 UTC
**_NVidia Geforce Experience version:_*3.9.0.61*
**Moonlight Embedded version:*2.4.3*
**Moonlight Embedded source:** _repository/included in distribution/compiled from source/..._
**Moonlight Embedded running on:*Raspberry pi w/ stretch*

sudo moonlight pair *ip of pc*
please enter blahblahblah
"Failed to pair to server: Failed to sign data"

It worked two days ago.  I'm guessing it is the new 3.9.0.61 geforce exp.  There was another poster on here that had the same problem and he was told:

"That isn't supposed to happen. Try to clean $XDG_CACHE_DIR/moonlight or ~/.cache/moonlight , maybe the keys got corrupted."

Then he said:
"Can someone help me how should i do this? Iam really a noob with CLI.
Thank you.
 @bodanu
bodanu commented 13 days ago
Never mind i did it :) now it works fine thank you so much !"

I don't know what he did, and I don't know how he did it.
I don't know how to "clean" anything and I assume you mean keys on the raspberry pi.  I did a fresh flash install of raspbian stretch and even uninstalled geforce experience and downgraded and no combination has worked.  It does stream to my phone.

Thank you for you time.  I am very inexperienced with linux.  I understand step by step instructions.

**Comment by irtimmer** [comment] 2017-09-07 17:51
Duplicate of #555

**Closed by irtimmer** 2017-09-07 17:51 UTC
Labels: duplicate
