### ISSUE TITLE
RPI2 moonlight-embedded with alsa crash  

### ISSUE THREAD

**Issue by coyote4k** [irtimmer/moonlight-embedded#307] opened 2016-02-08 17:23 UTC
Hello , 
RPI2 moonlight-embedded with alsa crash  
New and old version GFE and with limelight or moonlight result ..... crash . 

With all command -30fps -720 -localaudio and more crash 

raspi-config Force hdmi crash more 

apt-get remove alsa-utils and apt-get install alsa utils > sudo reboot = crash

apt-get install pulseaudio crash  

In 2016 impossible work a stream steam big picture on the RPI , you have a solution . 

Problème code Alsa.c or another problem maybe firmware RPI  , you have a solution ? 

info : Moonlight official work perfecly on my smatphone galaxy S2 

GFE or steam no in cause . i think firmware RPI2 or alsa.c need verify code and for this i'm not 
have a expérience . 

Big up for this problem open #126 ^^^^^^^ three night work for run moonlight correclty and are a silly man now : ) .

i start the stream and time bomb it's activated only picture or in game , 25s past Boooooom crash . fucking shit 

log : 

moonlight stream 192.168.1.2
Can't map (reverse_z)
Can't map (reverse_rz)
Initializing platform...done
Resolving host name...done
Starting RTSP handshake...done
Initializing control stream...done
Initializing video stream...done
Initializing audio stream...done
Initializing input stream...done
Starting control stream...done
Starting video stream...done
Starting audio stream...done
Starting input stream...done
Network dropped an entire frame
Waiting for IDR frame
IDR frame request sent
Waiting for IDR frame
Alsa error from writei: -32
Loss Stats: Transaction failed: 32
Stopping input stream...done
Stopping audio stream...done
Stopping video stream...done
Stopping control stream...done
Cleaning up input stream...done
Cleaning up audio stream...done
Cleaning up video stream...done
Cleaning up control stream...done
Terminating RTSP handshake...done
Cleaning up platform...done

**Comment by irtimmer** [comment] 2016-02-08 18:44
Duplicate of #301

**Closed by irtimmer** 2016-02-08 18:44 UTC
