### ISSUE TITLE
Starting control stream... Start A failed: 11

### ISSUE THREAD

**Issue by fl0wzr** [irtimmer/moonlight-embedded#706] opened 2018-11-22 11:28 UTC
NVidia Geforce Experience version: 3.16.0.122
Moonlight Embedded version: 2.4.7-1stretch1
Moonlight Embedded source: http://archive.itimmer.nl/raspbian/moonlight stretch main
Moonlight Embedded running on: Raspberry Pi
Moonlight Embedded running on distribution: Raspbian 

Verbose output `-verbose` of Moonlight Embedded:
Moonlight Embedded 2.4.7 (PI;ALSA;EMBEDDED)
Connect to 192.168.2.100...
NVIDIA GeForce GTX 970, GFE 3.16.0.122 (gs_04_11_25137997, 7.1.411.0)
Platform Raspberry Pi (Broadcom)
Loading mappingfile /usr/share/moonlight/gamecontrollerdb.txt
Stream 1920 x 1080, 30 fps, 10000 kbps
Initializing platform...done
Resolving host name...done
Starting RTSP handshake...done
Initializing control stream...done
Initializing video stream...done
Initializing audio stream...done
Initializing input stream...done
Starting control stream...Start A failed: 11
failed: 11
Cleaning up input stream...done
Cleaning up audio stream...done
Cleaning up video stream...done
Cleaning up control stream...done
Cleaning up platform...done

What is the expected result?
I'd like to stream my desktop (mstsc.exe) via moonlight on the raspberrypi. Pairing worked perfectly fine. 

What happens instead of that?
Only getting the error "Starting control stream...Start A failed: 11", the output continues a bit further but nothing is happening. 

Any help would be appreciated! Thank you. 

Edit 1:
Maybe issue #705 has the solution for this problem, seems like the library moonlight-common-c causes the trouble.

**Comment by irtimmer** [comment] 2018-11-22 11:40
Duplicate of #705

**Closed by irtimmer** 2018-11-22 11:40 UTC
Labels: duplicate
