### ISSUE TITLE
Support for NextThing.co CHIP?

### ISSUE THREAD

**Issue by andreacampanella** [irtimmer/moonlight-embedded#439] opened 2016-11-23 12:37 UTC
Sorry for the crude use of the Issue report, I tried to compile moonlight-embedded on the CHIP ( https://nextthing.co/pages/pocketchip ) the chip cpu is an Allwinner R8  ( http://linux-sunxi.org/R8 ) but the compilation ends, as expected with " No video output available " , any plan to port moonlight-embedded to this platform? I would be happy to be a tester if needed.

**Comment by irtimmer** [comment] 2017-03-18 18:05
Duplicate of #249 as NextThing.co CHIP also looks to use CedarX for video decoding

**Closed by irtimmer** 2017-03-18 18:05 UTC
Labels: duplicate
