### ISSUE TITLE
Controller problem ingame

### ISSUE THREAD

**Issue by Kheiryk** [irtimmer/moonlight-embedded#357] opened 2016-04-06 20:19 UTC
**NVidia Geforce Experience version: 2.11.2.55**
**Moonlight Embedded version: 2.2**
**Moonlight Embedded running on: Raspberry Pi 2 / Raspbian Jessy**

Hello, 
With the next version of Moonlight, i've resolved my problem for pair, but i've always my problem with my wired pad.

I start Raspbian and i check with **sudo xboxdrv **
![capture](https://cloud.githubusercontent.com/assets/16276098/14331302/04db296e-fc45-11e5-834e-6fb6c7096dec.JPG)

I must killall xobxdrv and execute **sudo rmmod xpad** for resolve it, after, i can push the buttons on my pad and the commands are displayed to the screen.

But, in game, i can't used my pad, nothing moves
In my rc.local, today
**xboxdrv --trigger-as-button --id 0 --led 2 --detach-kernel-driver --deadzone 4000 --silent &
sleep 1**

for start a game in example
**moonlight stream ip -1080 -app "Steam"**

Thanks

**Comment by irtimmer** [comment] 2016-04-06 20:29
Duplicate of #330

**Closed by irtimmer** 2016-04-06 20:29 UTC
