### ISSUE TITLE
Raspbian Stretch package missing

### ISSUE THREAD

**Issue by nlsdfnbch** [irtimmer/moonlight-embedded#579] opened 2017-10-28 14:49 UTC
I'm not able to download packages for the latest raspbian version (`stretch`). 

Added the following to `sources.list`:
`deb http://archive.itimmer.nl/raspbian/moonlight stretch main`

Have you published a package for this version yet?

**Comment by irtimmer** [comment] 2017-10-28 21:29
Duplicate of #549

**Closed by irtimmer** 2017-10-28 21:29 UTC
Labels: duplicate
