### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by BrutolocoW** [irtimmer/moonlight-embedded#717] opened 2018-12-08 05:26 UTC
**_NVidia Geforce Experience version:_**
Last version

**Moonlight Embedded version:**
Last version from "sudo apt-get install" from irtimmer

**Moonlight Embedded source:** _repository/included in distribution/compiled from source/..._

irtimmer strech

**Moonlight Embedded running on:** _Raspberry Pi/Cubox-i/Hummingboard/Other linux device/..._

Raspberry pi 2 B
**Moonlight Embedded running on distribution:** _Arch Linux/Raspbian/OpenELEC/..._

Raspbian stretch base clean install updated

**Verbose output `-verbose` of Moonlight Embedded:**

Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sat Dec  8 06:09:49 2018

pi@raspberrypi:~ $ moonlight stream -verbose
Moonlight Embedded 2.4.7 (PI;ALSA;EMBEDDED)
Searching for server...
Connect to 192.168.1.123...
NVIDIA GeForce GTX 1060 6GB, GFE 3.16.0.122 (gs_04_11_25137997, 7.1.411.0)
Platform Raspberry Pi (Broadcom)
Loading mappingfile /usr/share/moonlight/gamecontrollerdb.txt
Can't map (dpdown:+a1)
Can't map (dpleft:-a0)
Can't map (dpright:+a0)
Can't map (dpup:-a1)
Can't map (dpdown:+a1)
Can't map (dpleft:-a0)
Can't map (dpright:+a0)
Can't map (dpup:-a1)
Can't map (dpdown:+a1)
Can't map (dpleft:-a0)
Can't map (dpright:+a0)
Can't map (dpup:-a1)
Can't map (dpdown:+a1)
Can't map (dpleft:-a0)
Can't map (dpright:+a0)
Can't map (dpup:-a1)
Can't map (lefttrigger:+a3)
Can't map (righttrigger:-a3)
Can't map (dpdown:+a1)
Can't map (dpleft:-a0)
Can't map (dpright:+a0)
Can't map (dpup:-a1)
Can't map (dpdown:+a1)
Can't map (dpleft:-a0)
Can't map (dpright:+a0)
Can't map (dpup:-a1)
Stream 1280 x 720, 60 fps, 10000 kbps
Initializing platform...done
Resolving host name...done
Starting RTSP handshake...done
Initializing control stream...done
Initializing video stream...done
Initializing audio stream...done
Initializing input stream...done
Starting control stream...Start B failed: 11
failed: 11
Cleaning up input stream...done
Cleaning up audio stream...done
Cleaning up video stream...done
Cleaning up control stream...done
Cleaning up platform...done

**What is the expected result?**

It should work until reach the line
"Starting control stream...Start A failed: 11
failed: 11"

That line is new.

**What happens instead of that?**
It keeps in console running moonlight, with these line code until I cancel with control+alt+shift+q 

Doesn't show any image or sound.

**Comment by cgutman** [comment] 2018-12-08 05:52
Duplicate of #705

**Comment by posti85** [comment] 2018-12-08 17:17
That problem has been fixed in the source code but there aren't any release yet with the fix. You can try to compile the project yourself. I've detailed instructions for it: https://github.com/irtimmer/moonlight-embedded/issues/716#issuecomment-445205242

**Closed** 2018-12-08 17:30 UTC
