### ISSUE TITLE
gamestream window crashes when starting steam, sticks on rtsp handshake

### ISSUE THREAD

**Issue by tooandrew** [irtimmer/moonlight-embedded#275] opened 2015-12-14 03:55 UTC
when attempting to stream steam in big picture mode from my windows 10 desktop, the gamestream window opens, but crashes immediately, and the pi attempts to start the rtsp handshake for a long time then fails with error 110:

Initializing platform...done
Resolving host name...done
Starting RTSP handshake...connect() failed: 110
RTSP OPTIONS request failed: 110
failed: 110
EVIOCGRAB failed with error 16
EVIOCGRAB failed with error 16
EVIOCGRAB failed with error 16
EVIOCGRAB failed with error 16

however, when i stream assassin's creed syndicate ( moonlight stream -app ACS ), the stream is initialized just fine, the gamestream window stays open and everything works.

**Comment by H3llsing** [comment] 2015-12-22 23:02
use the search first!
Have you tried this ---> 
https://github.com/irtimmer/moonlight-embedded/issues/274  ?

**Comment by Athanaetos** [comment] 2015-12-24 19:55
Tried what?

**Comment by irtimmer** [comment] 2016-01-01 16:10
Duplicate of #274

**Closed by irtimmer** 2016-01-01 16:10 UTC
Labels: duplicate
