### ISSUE TITLE
keybord mapping bug

### ISSUE THREAD

**Issue by melzk** [irtimmer/moonlight-embedded#141] opened 2015-06-21 06:38 UTC
My keyboard's space key is maped as number 2 so every time i try to use space it make a number 2 press.

keyboard in the raspberry is set to international 105 keys keyboard in raspi config with swedish language

**Comment by irtimmer** [comment] 2015-06-21 11:23
Duplicate of  #55

**Closed by irtimmer** 2015-06-21 11:23 UTC
Labels: duplicate
