### ISSUE TITLE
Loss Stats: Transaction failed: 11

### ISSUE THREAD

**Issue by firepro20** [irtimmer/moonlight-embedded#384] opened 2016-06-17 10:20 UTC
**_NVidia Geforce Experience version:_** 2.11.3.5
**Moonlight Embedded version:** 2.2.0
**Moonlight Embedded running on:** Raspberry Pi 3

**Output of Moonlight Embedded:**

Moonlight Embedded 2.2.0 (EMBEDDED;PI)
Connect to 192.168.0.13...
NVIDIA GeForce GTX 970, GFE 2.11.3.6 (protocol version 7)
Stream 1280 x 720, 30 fps, 5000 kbps
Initializing platform...done
Resolving host name...done
Starting RTSP handshake...done
Initializing control stream...done
Initializing video stream...done
Initializing audio stream...done
Initializing input stream...done
Starting control stream...done
Starting video stream...done
Starting audio stream...done
Starting input stream...done
Returning RTP packet after queue overgrowth
Network dropped end of a frame
Waiting for IDR frame
IDR frame request sent
Returning RTP packet queued for too long
Received OOS audio data (expected 9759, but got 9762)
Waiting for IDR frame
Returning RTP packet queued for too long
Received OOS audio data (expected 10028, but got 10029)
Returning RTP packet after queue overgrowth
Network dropped end of a frame
Waiting for IDR frame
IDR frame request sent
Waiting for IDR frame
Returning RTP packet after queue overgrowth
Received OOS audio data (expected 10059, but got 10060)
Returning RTP packet queued for too long
Received OOS audio data (expected 14552, but got 14564)
Returning RTP packet queued for too long
Network dropped an entire frame
Waiting for IDR frame
Waiting for IDR frame
IDR frame request sent
Waiting for IDR frame
Returning RTP packet queued for too long
Network dropped middle of a frame
Waiting for IDR frame
IDR frame request sent
Waiting for IDR frame
Returning RTP packet after queue overgrowth
Network dropped middle of a frame
Waiting for IDR frame
IDR frame request sent
Returning RTP packet queued for too long
Received OOS audio data (expected 16877, but got 16884)
Waiting for IDR frame
Returning RTP packet after queue overgrowth
Network dropped middle of a frame
Waiting for IDR frame
IDR frame request sent
Returning RTP packet queued for too long
Received OOS audio data (expected 17064, but got 17070)
Waiting for IDR frame
Returning RTP packet after queue overgrowth
Network dropped end of a frame
Waiting for IDR frame
IDR frame request sent
Returning RTP packet queued for too long
Received OOS audio data (expected 18256, but got 18260)
Waiting for IDR frame
Returning RTP packet queued for too long
Network dropped beginning of a frame
Waiting for IDR frame
IDR frame request sent
Returning RTP packet queued for too long
Received OOS audio data (expected 19072, but got 19076)
Waiting for IDR frame
Returning RTP packet after queue overgrowth
Network dropped an entire frame
Waiting for IDR frame
IDR frame request sent
Returning RTP packet queued for too long
Received OOS audio data (expected 20952, but got 20973)
Waiting for IDR frame
Returning RTP packet queued for too long
Network dropped middle of a frame
Waiting for IDR frame
IDR frame request sent
Waiting for IDR frame
Returning RTP packet after queue overgrowth
Network dropped end of a frame
Waiting for IDR frame
IDR frame request sent
Returning RTP packet queued for too long
Received OOS audio data (expected 21228, but got 21232)
Waiting for IDR frame
Returning RTP packet after queue overgrowth
Network dropped middle of a frame
Waiting for IDR frame
IDR frame request sent
Waiting for IDR frame
Control stream received disconnect event
Loss Stats: Transaction failed: 11
Stopping input stream...done
Stopping audio stream...done
Stopping video stream...done
Stopping control stream...done
Cleaning up input stream...done
Cleaning up audio stream...done
Cleaning up video stream...done
Cleaning up control stream...done
Terminating RTSP handshake...done
Cleaning up platform...done

**What is the expected result?**

Smooth Stream at 30fps 720p

**What happens instead of that?**

Streams for a couple of seconds then disconnects. I am running the setup with ethernet connection through a repeater. So repeater connects wirelessly to router and pi connects with ethernet cable through repeater.

I did disable share/shadowplay so there is no other interference. I really do not know what I have else. OBS software has no running services when closed. No team viewer no other stream application

**Comment by irtimmer** [comment] 2016-06-17 10:30
Duplicate of #368

**Closed by irtimmer** 2016-06-17 10:30 UTC
