### ISSUE TITLE
Very slight, yet noticeable, delay in audio RPi 2

### ISSUE THREAD

**Issue by RockyGateway** [irtimmer/moonlight-embedded#235] opened 2015-10-31 01:37 UTC
Hello, I'll try to be as descriptive as I can and put as much info in as I can since no one else seems to be having this problem, at least I can't find anything relating to this, so maybe it's just me.

The issue I'm having is a very slight delay in the audio. I'd guess it's around 1/4th - 1/2 of a second delay. I don't know how I can properly measure how much the delay is. There is no lag anywhere else, until I go up to 1080 60fps. I'm usually running it at 720 60fps. I also don't use the input on the Pi itself, I use my controller through my streaming PC if that makes a difference.

This is on a Raspberry Pi 2 running Raspbian Jessie and the absolute latest version of Moonlight (Built from source a couple of days ago. Did this to see if it would help my audio delay, but it didn't), with these Overclock settings:

arm_freq=1050
core_freq=500
sdram_freq=550
over_voltage=6
avoid_safe_mode=1
force_turbo=0

It's also running on a wired connection.

On my PC my hardware is:
Intel i5 4690
16gb RAM
GTX 970
Latest GeForce experience and drivers

**Comment by irtimmer** [comment] 2015-11-24 20:34
Duplicate of #222

**Closed by irtimmer** 2015-11-24 20:34 UTC
