### ISSUE TITLE
Bannana Pro - How to run moonlight

### ISSUE THREAD

**Issue by Nooth** [irtimmer/moonlight-embedded#291] opened 2016-01-07 10:58 UTC
Hi,
I saw in prevoius posts that somebody added support for bannana (allwinner) in vdpau2 branch. How can I install it on bananian distribution? I tried to compile from source, but it fails due to some errors connected to raspberry pi hardware libraries. 

Is there any instruction how to make moonlight work on Banana? Is it possible?

I would be very gratefull if someone help me.

**Comment by irtimmer** [comment] 2016-01-16 13:41
Duplicate of #249

**Closed by irtimmer** 2016-01-16 13:41 UTC
