### ISSUE TITLE
RTSP: Failed to connect to UDP port 48010

### ISSUE THREAD

**Issue by lukakorica** [irtimmer/moonlight-embedded#610] opened 2018-01-13 11:32 UTC
Hello,
 I've encountered a problem while trying to stream anything from PC to my Raspberry Pi3. Whenever I try to do that i just get this error `Starting RTSP handshake...RTSP: Failed to connect to UDP port 48010` and `failed: -1`. I've tried enabling this port, even though that shouldn't matter, I've also tried to disabling my antivirus, reinstalling both the drivers and the GE, but nothing seems to fix it. Both devices are connected by LAN cables to the same router.
Though I can stream from my PC to my Android phone with no issues whatsoever. 
I have provided you with the Wireshark pcap of the two devices in question. 

[Wireshark capture](https://drive.google.com/open?id=1nMx-P69XtKrnCR0XACD-YiU7POrHQAeg)

**NVidia Geforce Experience version:** 3.12.0.79
**Moonlight Embedded version:** 2.4.4
**Moonlight Embedded running on:** Raspberry Pi3
**Moonlight Embedded running on distribution:** Raspbian Jessie

**Verbose output:**
> moonlight stream -720 -verbose
> Moonlight Embedded 2.4.4 (EMBEDDED;ALSA;PI)
> Searching for server...
> Connect to 192.168.0.18...
> NVIDIA GeForce GTX 960, GFE 3.12.0.79 (gs_04_04_23287129, 7.1.404.0)
> Platform Raspberry Pi (Broadcom)
> Loading mappingfile /usr/share/moonlight/gamecontrollerdb.txt
> Stream 1280 x 720, 60 fps, 10000 kbps
> Initializing platform...done
> Resolving host name...done
> Starting RTSP handshake...RTSP: Failed to connect to UDP port 48010
> failed: -1
> Cleaning up platform...done
> ^Cpi@kora_pi:~ $

**Comment by irtimmer** [comment] 2018-01-13 11:55
Duplicate of #609

**Closed by irtimmer** 2018-01-13 11:55 UTC
Labels: duplicate
